version: 2

updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      test:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
          - "FsUnit*"
          - "coverlet*"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - dependencies
