<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FsUnit.Xunit" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Library1.fs" />
    <Compile Include="Raw.fs" />
    <Compile Include="Obsolete.fs" />
    <Compile Include="Invocation.fs" />
    <Compile Include="Quotations.fs" />
    <Compile Include="OperatorValues.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSharp.Interop.Dynamic\FSharp.Interop.Dynamic.fsproj" />
  </ItemGroup>
</Project>
